/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TrustFlowLending {
  export type LoanStruct = {
    id: BigNumberish;
    borrower: AddressLike;
    amount: BigNumberish;
    interestRate: BigNumberish;
    termMonths: BigNumberish;
    riskScore: BigNumberish;
    purpose: string;
    status: BigNumberish;
    totalFunded: BigNumberish;
    totalRepaid: BigNumberish;
    createdAt: BigNumberish;
    fundedAt: BigNumberish;
    monthlyPayment: BigNumberish;
    platformFee: BigNumberish;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrower: string,
    amount: bigint,
    interestRate: bigint,
    termMonths: bigint,
    riskScore: bigint,
    purpose: string,
    status: bigint,
    totalFunded: bigint,
    totalRepaid: bigint,
    createdAt: bigint,
    fundedAt: bigint,
    monthlyPayment: bigint,
    platformFee: bigint
  ] & {
    id: bigint;
    borrower: string;
    amount: bigint;
    interestRate: bigint;
    termMonths: bigint;
    riskScore: bigint;
    purpose: string;
    status: bigint;
    totalFunded: bigint;
    totalRepaid: bigint;
    createdAt: bigint;
    fundedAt: bigint;
    monthlyPayment: bigint;
    platformFee: bigint;
  };

  export type InvestmentStruct = {
    lender: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type InvestmentStructOutput = [
    lender: string,
    amount: bigint,
    timestamp: bigint
  ] & { lender: string; amount: bigint; timestamp: bigint };

  export type RepaymentStruct = {
    borrower: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type RepaymentStructOutput = [
    borrower: string,
    amount: bigint,
    timestamp: bigint
  ] & { borrower: string; amount: bigint; timestamp: bigint };
}

export interface TrustFlowLendingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveLoan"
      | "borrowerLoans"
      | "createLoan"
      | "fundLoan"
      | "getBorrowerLoanIds"
      | "getLenderInvestmentIds"
      | "getLoan"
      | "getLoanCount"
      | "getLoanInvestments"
      | "getLoanRepayments"
      | "getLoans"
      | "getTotalOwed"
      | "lenderInvestments"
      | "loanCount"
      | "loanInvestments"
      | "loanRepayments"
      | "loans"
      | "owner"
      | "platformFeeBps"
      | "rejectLoan"
      | "repayLoan"
      | "setPlatformFee"
      | "totalPlatformFees"
      | "transferOwnership"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawn"
      | "LoanActivated"
      | "LoanApproved"
      | "LoanCreated"
      | "LoanFullyRepaid"
      | "LoanFunded"
      | "LoanRejected"
      | "LoanRepayment"
      | "PlatformFeeUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoan",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowerLoanIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLenderInvestmentIds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanInvestments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanRepayments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoans",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalOwed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lenderInvestments",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loanCount", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "loanInvestments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "loanRepayments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPlatformFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fundLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowerLoanIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLenderInvestmentIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLoanRepayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalOwed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lenderInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loanCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "loanInvestments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "loanRepayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rejectLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalPlatformFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanActivatedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanApprovedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    interestRate: BigNumberish,
    termMonths: BigNumberish,
    purpose: string
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    amount: bigint,
    interestRate: bigint,
    termMonths: bigint,
    purpose: string
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
    interestRate: bigint;
    termMonths: bigint;
    purpose: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFullyRepaidEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFundedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    lender: AddressLike,
    amount: BigNumberish,
    totalFunded: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    lender: string,
    amount: bigint,
    totalFunded: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    lender: string;
    amount: bigint;
    totalFunded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRejectedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaymentEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    totalRepaid: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    amount: bigint,
    totalRepaid: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
    totalRepaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [newFeeBps: BigNumberish];
  export type OutputTuple = [newFeeBps: bigint];
  export interface OutputObject {
    newFeeBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrustFlowLending extends BaseContract {
  connect(runner?: ContractRunner | null): TrustFlowLending;
  waitForDeployment(): Promise<this>;

  interface: TrustFlowLendingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  borrowerLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createLoan: TypedContractMethod<
    [
      _amount: BigNumberish,
      _interestRate: BigNumberish,
      _termMonths: BigNumberish,
      _riskScore: BigNumberish,
      _purpose: string
    ],
    [bigint],
    "nonpayable"
  >;

  fundLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  getBorrowerLoanIds: TypedContractMethod<
    [_borrower: AddressLike],
    [bigint[]],
    "view"
  >;

  getLenderInvestmentIds: TypedContractMethod<
    [_lender: AddressLike],
    [bigint[]],
    "view"
  >;

  getLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [TrustFlowLending.LoanStructOutput],
    "view"
  >;

  getLoanCount: TypedContractMethod<[], [bigint], "view">;

  getLoanInvestments: TypedContractMethod<
    [_loanId: BigNumberish],
    [TrustFlowLending.InvestmentStructOutput[]],
    "view"
  >;

  getLoanRepayments: TypedContractMethod<
    [_loanId: BigNumberish],
    [TrustFlowLending.RepaymentStructOutput[]],
    "view"
  >;

  getLoans: TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [TrustFlowLending.LoanStructOutput[]],
    "view"
  >;

  getTotalOwed: TypedContractMethod<[_loanId: BigNumberish], [bigint], "view">;

  lenderInvestments: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  loanCount: TypedContractMethod<[], [bigint], "view">;

  loanInvestments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        lender: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  loanRepayments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        borrower: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        borrower: string;
        amount: bigint;
        interestRate: bigint;
        termMonths: bigint;
        riskScore: bigint;
        purpose: string;
        status: bigint;
        totalFunded: bigint;
        totalRepaid: bigint;
        createdAt: bigint;
        fundedAt: bigint;
        monthlyPayment: bigint;
        platformFee: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  rejectLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  repayLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  setPlatformFee: TypedContractMethod<
    [_newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalPlatformFees: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "borrowerLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createLoan"
  ): TypedContractMethod<
    [
      _amount: BigNumberish,
      _interestRate: BigNumberish,
      _termMonths: BigNumberish,
      _riskScore: BigNumberish,
      _purpose: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getBorrowerLoanIds"
  ): TypedContractMethod<[_borrower: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLenderInvestmentIds"
  ): TypedContractMethod<[_lender: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [TrustFlowLending.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoanCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLoanInvestments"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [TrustFlowLending.InvestmentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoanRepayments"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [TrustFlowLending.RepaymentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoans"
  ): TypedContractMethod<
    [_offset: BigNumberish, _limit: BigNumberish],
    [TrustFlowLending.LoanStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalOwed"
  ): TypedContractMethod<[_loanId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "lenderInvestments"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loanInvestments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        lender: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "loanRepayments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint] & {
        borrower: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        borrower: string;
        amount: bigint;
        interestRate: bigint;
        termMonths: bigint;
        riskScore: bigint;
        purpose: string;
        status: bigint;
        totalFunded: bigint;
        totalRepaid: bigint;
        createdAt: bigint;
        fundedAt: bigint;
        monthlyPayment: bigint;
        platformFee: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rejectLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalPlatformFees"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[_to: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "LoanActivated"
  ): TypedContractEvent<
    LoanActivatedEvent.InputTuple,
    LoanActivatedEvent.OutputTuple,
    LoanActivatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanApproved"
  ): TypedContractEvent<
    LoanApprovedEvent.InputTuple,
    LoanApprovedEvent.OutputTuple,
    LoanApprovedEvent.OutputObject
  >;
  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFullyRepaid"
  ): TypedContractEvent<
    LoanFullyRepaidEvent.InputTuple,
    LoanFullyRepaidEvent.OutputTuple,
    LoanFullyRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRejected"
  ): TypedContractEvent<
    LoanRejectedEvent.InputTuple,
    LoanRejectedEvent.OutputTuple,
    LoanRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepayment"
  ): TypedContractEvent<
    LoanRepaymentEvent.InputTuple,
    LoanRepaymentEvent.OutputTuple,
    LoanRepaymentEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawn(address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "LoanActivated(uint256)": TypedContractEvent<
      LoanActivatedEvent.InputTuple,
      LoanActivatedEvent.OutputTuple,
      LoanActivatedEvent.OutputObject
    >;
    LoanActivated: TypedContractEvent<
      LoanActivatedEvent.InputTuple,
      LoanActivatedEvent.OutputTuple,
      LoanActivatedEvent.OutputObject
    >;

    "LoanApproved(uint256)": TypedContractEvent<
      LoanApprovedEvent.InputTuple,
      LoanApprovedEvent.OutputTuple,
      LoanApprovedEvent.OutputObject
    >;
    LoanApproved: TypedContractEvent<
      LoanApprovedEvent.InputTuple,
      LoanApprovedEvent.OutputTuple,
      LoanApprovedEvent.OutputObject
    >;

    "LoanCreated(uint256,address,uint256,uint256,uint256,string)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanFullyRepaid(uint256)": TypedContractEvent<
      LoanFullyRepaidEvent.InputTuple,
      LoanFullyRepaidEvent.OutputTuple,
      LoanFullyRepaidEvent.OutputObject
    >;
    LoanFullyRepaid: TypedContractEvent<
      LoanFullyRepaidEvent.InputTuple,
      LoanFullyRepaidEvent.OutputTuple,
      LoanFullyRepaidEvent.OutputObject
    >;

    "LoanFunded(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanRejected(uint256)": TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;
    LoanRejected: TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;

    "LoanRepayment(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanRepaymentEvent.InputTuple,
      LoanRepaymentEvent.OutputTuple,
      LoanRepaymentEvent.OutputObject
    >;
    LoanRepayment: TypedContractEvent<
      LoanRepaymentEvent.InputTuple,
      LoanRepaymentEvent.OutputTuple,
      LoanRepaymentEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
  };
}
